# -*- coding: utf-8 -*-
"""Funciones_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16M44rPkgZDc8cMxNhnMUwEnjxq82YtgT
"""

def verAsientosDisponibles():
  bandera_full = True
  for f in range(7):
    for c in range(6):
      if vuelo[f,c] != 'X':
        bandera_full = False
  if bandera_full == False:
    print(f"|  {vuelo[0,0]}    {vuelo[0,1]}    {vuelo[0,2]}      {vuelo[0,3]}    {vuelo[0,4]}    {vuelo[0,5]} |")
    print(f"|  {vuelo[1,0]}    {vuelo[1,1]}    {vuelo[1,2]}     {vuelo[1,3]}   {vuelo[1,4]}   {vuelo[1,5]} |")
    print(f"| {vuelo[2,0]}   {vuelo[2,1]}   {vuelo[2,2]}     {vuelo[2,3]}   {vuelo[2,4]}   {vuelo[2,5]} |")
    print(f"| {vuelo[3,0]}   {vuelo[3,1]}   {vuelo[3,2]}     {vuelo[3,3]}   {vuelo[3,4]}   {vuelo[3,5]} |")
    print(f"| {vuelo[4,0]}   {vuelo[4,1]}   {vuelo[4,2]}     {vuelo[4,3]}   {vuelo[4,4]}   {vuelo[4,5]} |")
    print("|______________   ______________|")
    print("|______________   ______________|")
    print(f"| {vuelo[5,0]}   {vuelo[5,1]}   {vuelo[5,2]}     {vuelo[5,3]}   {vuelo[5,4]}   {vuelo[5,5]} |")
    print(f"| {vuelo[6,0]}   {vuelo[6,1]}   {vuelo[6,2]}     {vuelo[6,3]}   {vuelo[6,4]}   {vuelo[6,5]} |")

def comprarAsiento(nombre,rut,telefono,banco):
  pasaje = input("Cual asiento desea comprar?(Ingrese el número):\n")
  msg = ""
  bandera_libre = False
  for f in range(7):
    for c in range(6):
      if pasaje == vuelo[f,c]:
        vuelo[f,c] = 'X'
        lista_indice1.append(f)
        lista_indice2.append(c)
        bandera_libre = True
  if bandera_libre:
    print("Asiento correcto.")
    lista_pasaje.append(pasaje)
    lista_nombre.append(nombre)
    lista_rut.append(rut)
    lista_telefono.append(telefono)
    lista_banco.append(banco)
    if int(pasaje) >= 1 and int(pasaje) <= 30:
      total = 78900
      if  banco == 'bancoDuoc':
        dsct = int(total * 0.85)
        msg = (f"Al tener una cuenta en el banco Duoc, usted ha ganado un descuento de un 15%!\nSu total es de {dsct}")
      else:
        msg = (f"Su total es de {total}")
    else:
      total = 240000
      if  banco == 'bancoDuoc':
        dsct = int(total * 0.85)
        msg = (f"Al tener una cuenta en el banco Duoc, usted ha ganado un descuento de un 15%!\nSu total es de {dsct}")
      else:
        msg = (f"Su total es de {total}")
  else:
    msg = 'Asiento invalido o ocupado.'
  
  return msg

def liberarAsiento(pasaje):
    if pasaje in lista_pasaje:
      print("Pasaje valido.")
      indice_pasaje = 0
      for x in lista_pasaje:
        if pasaje == x:
          indx_pas = indice_pasaje
        indice_pasaje +=1

      indice1 = lista_indice1[indx_pas]
      indice2 = lista_indice2[indx_pas]
      vuelo[indice1,indice2] = pasaje
      del lista_pasaje[indx_pas]
      del lista_rut[indx_pas]
      del lista_nombre[indx_pas]
      del lista_telefono[indx_pas]
      del lista_banco[indx_pas]
      del lista_indice1[indx_pas]
      del lista_indice2[indx_pas]
      print("Asiento liberado, datos del cliente eliminados. \n\n")

    else:
      print("Ese pasaje no ha sido comprado.")

def modificarDatos():
  rut = input("Ingrese el rut del pasajero a modificar:\n")
  pasaje = input("Ingrese el asiento del pasajero a modificar:\n")
  indice_rut = 0
  if rut in lista_rut:
    if pasaje in lista_pasaje:
      for x in lista_rut:
        if x == rut:
          indx = indice_rut
        indice_rut += 1
      if lista_rut[indx] == rut and lista_pasaje[indx] == pasaje:
        op2 = 0
        while op2 != 3:
          print(" = = = Que datos desea modificar? = = =")
          print("1.- Nombre")
          print("2.- Telefono")
          print("3.- Volver al menú principal.")
          op2 = int(input())

          if op2 ==1:
            nombre = input("Ingrese nuevo nombre:\n")
            lista_nombre[indx] = nombre
            print("Dato actualizado correctamente.\n\n\n")
          elif op2 == 2:
            telefono = input("Ingrese nuevo telefono:\n")
            lista_telefono[indx] = telefono
            print("Dato actualizado correctamente.\n\n\n")
          elif op2 == 3:
            print("Volviendo al menú principal. \n\n\n")

      else:
        print("Datos no coinciden.")
    else:
      print("Ese pasaje no ha sido comprado.")
  else:
    print("Nadie con ese rut ha comprado un pasaje.")