# -*- coding: utf-8 -*-
"""tipo_prueba.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YHpNcF5cAFNe8haPPC5fLJoTsZ3-Yyz-
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %run '/content/drive/MyDrive/Funciones_test.ipynb'

import numpy as np
lista_pasaje = []
lista_nombre = []
lista_rut = []
lista_telefono = []
lista_banco = []
lista_indice1 = []
lista_indice2= []

vuelo = np.array([['1','2','3','4','5','6'],
                  ['7','8','9','10','11','12'],
                  ['13','14','15','16','17','18'],
                  ['19','20','21','22','23','24'],
                  ['25','26','27','28','29','30'],
                  ['31','32','33','34','35','36'],
                  ['37','38','39','40','41','42']])
op = 0
while op != 5:
  print(" ===== Menú =====")
  print("1.- Ver asientos disponibles.")
  print("2.- Comprar asiento")
  print("3.- Anular Vuelo")
  print("4.- Modificar datos de pasajero")
  print("5.- Salir")

  op = int(input())
  if op == 1:
    verAsientosDisponbiles()
  elif op == 2:
    print("Ingrese sus datos:")
    nombre = input("Ingrese su nombre:\n")
    rut = input("Ingrese su rut:\n")
    telefono = input("Ingrese su número telefonico: \n")
    banco= input("Ingrese su banco:\n")
    print(comprarAsiento(nombre,rut,telefono,banco))
  elif op == 3:
    pasaje = input("Ingrese el número del asiento que desea liberar:")
    liberarAsiento(pasaje)
  elif op == 4:
    modificarDatos()
  elif op == 5:
    print("Gracias por preferirnos, tenga un buen día.")

